### ISSUE TITLE
Hi - where can I ask questions about JActiveModule?

### ISSUE THREAD

**Issue by NomiCentarix** [idekerlab/jActiveModules#3]
It seems no one is here...

**Comment by coleslaw481** [comment]
Hi,
Sorry on the late reply. You can ask your question here and we can do our best to answer. 

Or you could also post a question here (and tag with cytoscape): https://stackoverflow.com/questions/tagged/cytoscape?sort=newest

**Comment by coleslaw481** [comment]
Going to close this. Just make a new issue with your question.
